apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ztunnel
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  project: default
  source:
    chart: ztunnel
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: "1.23.5"
    helm:
      parameters:
      - name: profile
        value: ambient
      values: |
        resourceName: ztunnel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true