# secrets
minioSecret:
  accessKeyId: ""
  secretAccessKey: ""

loki:
  loki:
    commonConfig:
      replication_factor: 1
    schemaConfig:
      configs:
        - from: 2024-04-01
          store: tsdb
          object_store: s3
          schema: v13
          index:
            prefix: loki_index_
            period: 24h
    ingester:
      chunk_encoding: snappy
    tracing:
      enabled: true
    querier:
      max_concurrent: 2

    deploymentMode: SingleBinary
    singleBinary:
      replicas: 1
      resources:
        limits:
          memory: 2Gi
        requests:
          cpu: 500m
          memory: 1Gi
      extraEnv:
        - name: GOMEMLIMIT
          value: 1750MiB

    chunksCache:
      writebackSizeLimit: 10MB

    storage:
      bucketNames:
        chunks: loki-chunks
        ruler: loki-ruler
        admin: loki-admin
      type: s3
      s3:
        endpoint: http://10.10.8.15:9000
        region: proxmox-1
        accessKeyId: "PLACEHOLDER"  # Replace with actual value or secret reference
        secretAccessKey: "PLACEHOLDER"  # Replace with actual value or secret reference
        insecure: true

    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0
    ingester:
      replicas: 0
    querier:
      replicas: 0
    queryFrontend:
      replicas: 0
    queryScheduler:
      replicas: 0
    distributor:
      replicas: 0
    compactor:
      replicas: 0
    indexGateway:
      replicas: 0
    bloomCompactor:
      replicas: 0
    bloomGateway:
      replicas: 0
