{{- if .Values.httpRoutes.enabled }}
{{- range .Values.httpRoutes.routes }}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  {{- if .labels }}
  labels:
    {{- toYaml .labels | nindent 4 }}
  {{- end }}
  {{- if .annotations }}
  annotations:
    {{- toYaml .annotations | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    - name: {{ .parentRef.gateway }}
      namespace: {{ .parentRef.namespace }}
  hostnames:
    - {{ .hostname | quote }}
  rules:
    - matches:
        - path:
            type: {{ .path.type | default "PathPrefix" }}
            value: {{ .path.value | default "/" }}
      backendRefs:
        - name: {{ .backend.name }}
          port: {{ .backend.port }}
{{- end }}
{{- end }}
