apiVersion: v1
kind: Secret
metadata:
  name: {{ include "parent-chart.fullname" . }}-minio-credentials | quote
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "parent-chart.labels" . | nindent 4 }}
type: Opaque
data:
  accessKeyId: {{ .Values.minioSecret.accessKeyId | default "" | b64enc }}
  secretAccessKey: {{ .Values.minioSecret.secretAccessKey | default "" | b64enc }}
