apiVersion: v1
kind: Secret
metadata:
  name: {{ include "parent-chart.fullname" . }}-minio-credentials
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "parent-chart.labels" . | nindent 4 }}
type: Opaque
data:
  accessKeyId: "PLACEHOLDER"  # Placeholder value
  secretAccessKey: "PLACEHOLDER"  # Placeholder value
