{{- if .Values.httpRoutes.enabled }}
{{- range .Values.httpRoutes.routes }}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  {{- if .Values.labels }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    - name: {{ .Values.parentRef.gateway }}
      namespace: {{ .Values.parentRef.namespace }}
  hostnames:
    - {{ .Values.hostname | quote }}
  rules:
    - matches:
        - path:
            type: {{ .Values.path.type | default "PathPrefix" }}
            value: {{ .Values.path.value | default "/" | quote }}
      backendRefs:
        - name: {{ .Values.backend.name }}
          port: {{ .Values.backend.port }}
